# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f79f12a11be4953c97b856c1772e4761ba3c9e2ad4ccb75ea99253900e5d7d1d90467138f6733a6ec7deae5948026be4e572c6450c6c64b18bc47e7e3343676

test:
  secret_key_base: a52aa535c20cb09e80aad9ec574552649792ac0906acb9606e078ea803d0d6328dc13cd80d05be2ed84fe5686933b920904ce9420974676244c309e106cabea8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
